# Generated by Django 3.2.11 on 2022-03-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('order', 'Order'), ('accepted', 'Accepted'), ('finished', 'Finished')], default='order', max_length=15),
        ),
    ]
